### ISSUE TITLE
Permissions for using the KEDA logo

### ISSUE THREAD

**Issue by CarloGarcia** [kedacore/governance#10]
What are the rules (or permissions required) in order to use the KEDA logo? For example to print on t-shirts, stickers or mugs and potentially selling said items with the KEDA logo on them? Where could explicit permission be obtained from?

**Comment by tomkerkhove** [comment]
I'll need to ping @caniszczyk because this is more related to CNCF.

What would be the goal of selling these?

**Comment by zroubalik** [comment]
> What would be the goal of selling these?

+1

btw there's KEDA Swag Store: https://merch.keda.sh/

**Comment by CarloGarcia** [comment]
I know an artist (ceramicist) who makes handmade bespoke cups on request (for example see https://twitter.com/B1zTalker/status/1344948203326734337?s=20). If someone orders a cup with a KEDA logo on it, does the artist (or anyone) need permission first before they can make and/or sell the cup?

Many thanks for the link to the swag store. Will check it out.

**Comment by tomkerkhove** [comment]
All CNCF projects are bound by: https://www.linuxfoundation.org/trademark-usage/.

> The Linux Foundation permits the use of its trademarks for private and personal use to make t-shirts, stickers, and caps for yourself and your friends (meaning people from whom you don’t receive anything of value in return) in a manner that is consistent with the preservation of the goodwill and value of the mark.

**Comment by tomkerkhove** [comment]
I checked with CNCF and we can vote on this as maintainers - What do you think @zroubalik @jeffhollan @ahmelsayed @anirudhgarg?

👍 or 👎

**Comment by zroubalik** [comment]
How many cups do I receive for a vote up? 😄 (just kidding)

**Comment by zroubalik** [comment]
@tomkerkhove out of curiosity, how does this voting goes along with the trademark-usage that you linked here above? To be clear, I don't have a problem with the original request, but I don't see how does this fit with this paragraph:

>The Linux Foundation permits the use of its trademarks for private and personal use to make t-shirts, stickers, and caps for yourself and your friends (meaning people from whom you don’t receive anything of value in return) in a manner that is consistent with the preservation of the goodwill and value of the mark.

**Comment by tomkerkhove** [comment]
I checked with @caniszczyk offline, but maybe he can elaborate here?

**Comment by caniszczyk** [comment]
@zroubalik as long as the cups are made for personal usage and for the maintainers/friends, we are OK with that. CNCF is even happy to cover the cost for cups for the maintainers of KEDA if that helps.

**Comment by zroubalik** [comment]
@caniszczyk thanks for the clarification, I just wasn't sure, since the original request talked about potential selling of the stuff. 

I am not against the idea, I am completely fine with folks making a KEDA swag, just wanted to double check 😉

**Comment by jeffhollan** [comment]
Yep I'm cool with people using logo for swag they aren't re-selling

**Comment by tomkerkhove** [comment]
Can we close this issue @CarloGarcia ?

**Comment by CarloGarcia** [comment]
Apologies for the delay - this issue can definitely be closed. It's clear for me.

Many thanks!
