### ISSUE TITLE
Stepping down as a maintainer

### ISSUE THREAD

**Issue by ahmelsayed** [kedacore/governance#108]
Hi all,

I want to step down as a maintainer of KEDA given my lack of any recent contributions to the project and limited availability otherwise.

I'd like to sincerely thank Jeff, Jorge, Tom, and Zbynek for all their amazing efforts in maintaining and driving the project to where it's today.

**Comment by tomkerkhove** [comment]
I'm sorry to hear but I understand why you are making this decision.

Thank you very much for starting and driving the project, allowing it to grow to what is has become today

**Comment by zroubalik** [comment]
@ahmelsayed sorry to hear that! I would like to thank you for your fundamental contributions to the KEDA. Thanks!

**Comment by JorTurFer** [comment]
hey @ahmelsayed, sorry to heard it but it's totally understandable.

Thanks a lot for you invaluable contributions!
