### ISSUE TITLE
Recommend Jan Wozniak as new maintainer

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#114]
For a while @wozniakjan has been contributing a lot in different areas and has done some great work in KEDA. 

I think his sense of responsibility and the effort he puts in to KEDA is inspiring and he would be a good maintainer to help us with the day-to-day maintainership work and help define the future of KEDA more.

**Comment by tomkerkhove** [comment]
Any thoughts @kedacore/keda-maintainers? Also, would you be interested @wozniakjan?

**Comment by zroubalik** [comment]
I fully approve this 💯

**Comment by wozniakjan** [comment]
thank you so much, the acknowledgement means a lot to me! I will try to increase my involvement as much as my wife allows me, and hang out with you guys for many releases :)

**Comment by tomkerkhove** [comment]
> I will try to increase my involvement as much as my wife allows me

Oh you don't need to increase anything! Make sure to enjoy life every now and then :)

**Comment by JorTurFer** [comment]
I fully agree! He has been doing a really great job, not only with coding but also supporting users and contributors. My vote is a huge yes!

**Comment by tomkerkhove** [comment]
Great - What about you @jeffhollan?

**Comment by jeffhollan** [comment]
Full support

**Comment by tomkerkhove** [comment]
🎉
