### ISSUE TITLE
Provide self-hosted ARM runner

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#12]
ARM is becoming a major aspect for workloads such as edge and we've received requests to provide an ARM-based image (https://github.com/kedacore/keda/issues/779).

GitHub Actions does not provide an ARM runner, but CNCF allows us to request a bare metal machine ([link](https://github.com/cncf/cluster)) on which we could run a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).

If we want to, we can request one but the [following requirements apply](https://github.com/cncf/cluster#usage-guidelines):
> - Code being run must be 100 percent open source and must not include any sensitive data.
> - Testing should involve cloud native computing, meaning containerization, microservices, orchestration or some combination.
> - You agree to write a blog post later about your experiences with the CIL.
> - Priority is given first to CNCF projects, then to developers from CNCF member companies and then to any open source developer.
> - Resources are limited so we may ask you to reduce your usage when there is high demand for the available credits from Equinix Metal ($1,000,000 per year).

What do you think?

**Comment by zroubalik** [comment]
This is looking good, I think that we follow all the requirements, so there shouldn't be a problem.

**Comment by jeffhollan** [comment]
Issued request here https://github.com/cncf/cluster/issues/163

**Comment by tomkerkhove** [comment]
Any update on this @jeffhollan ?

**Comment by JorTurFer** [comment]
Any update?
ARM is a reality in AWS with Graviton nodes. We are thinking in migrate our workloads to ARM because Graviton saves a lot of money for example.
Of course, having more than one nodepools we could have also AMD nodes, but it would be amazing if KEDA runs on ARM too

**Comment by jeffhollan** [comment]
> Any update on this @jeffhollan ?

Yes we have the infra issued from CNCF, would need someone to wire up that infra with GitHub Actions runners and include in our e2e tests (as well as make any adjustments needed to make it work well)

**Comment by tomkerkhove** [comment]
Feel free to send me the details and I can take a look!

**Comment by JorTurFer** [comment]
Nice!!! Supporting ARM could be an incredible feature :) 
Let me know if I can help in anything there

**Comment by tomkerkhove** [comment]
Self-hosted ARM64 runner for GitHub Actions is available.

```yaml
runs-on: keda-arm64
```

I will add the SSH keys to 1Password later on.

**Comment by JorTurFer** [comment]
But we will need a kubernetes cluster with ARM nodes in order to run e2e test there.
Maybe we can install a local cluster for that :thinking:

**Comment by zroubalik** [comment]
That's right, @tomkerkhove do you know how many machines or how big they are? We can run a reduced e2e tests on that, just a smoke check that the build is correct.

**Comment by tomkerkhove** [comment]
It's up and running.
