### ISSUE TITLE
Tracking integrations with other technologies

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#14]
I've recently opened a few issues for integration with other technologies:

**Azure Service Operator**: https://github.com/Azure/azure-service-operator/issues/1377
**Crossplane**:
- ALibaba Cloud: https://github.com/crossplane/provider-alibaba/issues/57
- Rook: https://github.com/crossplane/provider-rook/issues/94
- GCP: https://github.com/crossplane/provider-gcp/issues/304
- AWS: https://github.com/crossplane/provider-aws/issues/537
- Azure: https://github.com/crossplane/provider-azure/issues/221

I was thinking, would it make sense to document in a page what the tools are that we integrate with and they can use KEDA with?

This could be in our docs, in this repo or in something like `kedacore/integrations`.

**Comment by tomkerkhove** [comment]
WDYT @zroubalik @jeffhollan @anirudhgarg @ahmelsayed ?

**Comment by ahmelsayed** [comment]
I'm not very familiar with crossplane, but I'm assuming it's a way to standardize operators across clouds for those cloud's services, but just managed through Kubernetes, right? Based on the issues you have above though, they don't yet support the /scale subresource, right?

**Comment by tomkerkhove** [comment]
Yes indeed, but Crossplane is just an example of one integration - But it's just an idea though.

**Comment by tomkerkhove** [comment]
This could also be part of keda.sh, which might be a better place under /integrations or so.

**Comment by tomkerkhove** [comment]
We've agreed to add this to keda.sh, tracking in https://github.com/kedacore/keda-docs/issues/387
