### ISSUE TITLE
Request to step down from the role of Maintainer of KEDA org 

### ISSUE THREAD

**Issue by anirudhgarg** [kedacore/governance#17]
Opening this issue to request to step down from the role of a Maintainer from KEDA org. This is to reduce the number of maintainers from Microsoft (Currently they are 3 including me) and also not being able to give enough time.

**Comment by tomkerkhove** [comment]
I'm sorry to hear that but respect your decision, you will be missed!

**Comment by zroubalik** [comment]
Sorry to hear that! Thanks a lot and good luck Anirudh
