### ISSUE TITLE
Use dedicated Azure subscription

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#31]
Request Azure funds for open-source projects through new program:
https://cloudblogs.microsoft.com/opensource/2021/09/28/announcing-azure-credits-for-open-source-projects/

**Comment by tomkerkhove** [comment]
Requested!

**Comment by tomkerkhove** [comment]
Azure funds for open-source is only applicable for OSS projects that are CNCF Sandbox or not part of CNCF. For Incubation/Graduation CNCF cloud credits is required for which Azure has no support.

The Azure Container Apps team, however, is more than happy to sponsor an Azure subscription which has been set up and will be activated soon! 🎉🎉🎉

**Comment by tomkerkhove** [comment]
The subscription should become active on May 1st.

**Comment by zroubalik** [comment]
Great news! Thank @tomkerkhove and all related Azure Teams!

**Comment by JorTurFer** [comment]
Thanks for pushing the topic! ❤️

**Comment by tomkerkhove** [comment]
Subscription `afbc9e97-8dea-44a4-ad1c-ac577f221821` is live and maintainers were invited!
