### ISSUE TITLE
Introduce "Contributors" group for frequent contributors

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#32]
Introduce "Contributors" group for frequent contributors so that we can assign the users/group to issues.

This should be documented in the repo when people are being considered to be added and what it means to become one.

**Comment by JorTurFer** [comment]
Should we push this topic @kedacore/keda-maintainers ? The adoption is growing there are some new people contributing, maybe if we move this topic, they will be more engaged and open to continue contributing 😄

**Comment by geoffrey1330** [comment]
Hi @tomkerkhove How do one become a member of keda, what's the requirements to become a member?
cc @zroubalik @JorTurFer

**Comment by tomkerkhove** [comment]
We did not formally close this so no requirements for now

**Comment by JorTurFer** [comment]
Maybe it's a good moment for working on this? 🤔

**Comment by JorTurFer** [comment]
I think that [this issue](https://github.com/kedacore/governance/issues/107) can cover better the case. If you agree, we can close this
