### ISSUE TITLE
Consideration for Jorge Turrado as maintainer

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/governance#38]
Hi!
I'm lover of KEDA because I think that it covers an existing gap in Kubernetes autoscaling and open the doors to a lot of several event-driven scenarios from nowadays. 
If you could consider me as a KEDA maintainer, it'd be amazing

Thank you for your time!

**Comment by tomkerkhove** [comment]
You've been doing a ton of contributions to not only our core, but also the documentation, testing and reviews.

I support this 💯%.

**Comment by zroubalik** [comment]
Agree, you have done a lot of great contributions!

I support this as well!

**Comment by tomkerkhove** [comment]
Technically we have a pass since @jeffhollan @ahmelsayed and myself share the same vote, but will allow them to reply as well :)

**Comment by jeffhollan** [comment]
Absolutely support!

**Comment by ahmelsayed** [comment]
I support this also!

**Comment by tomkerkhove** [comment]
I think that's pretty clear -  Congrats @JorTurFer and welcome! 🎉
I will do the rest of the onboarding next week.
