### ISSUE TITLE
Onboard Jorge Turrado as new maintainer 🎉

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#42]
## Tasklist

- [x] Access to 1Password (@tomkerkhove)
- [x] Access to CNCF DLs (@amye)
- [x] Access to GitHub groups (@tomkerkhove)
- [ ] Add to CODEOWNERS file in our repos

Follow-up for #38

**Comment by tomkerkhove** [comment]
@amye would it be possible to add @JorTurFer to our distribution list please?

**Comment by tomkerkhove** [comment]
Added to maintainer group

**Comment by amye** [comment]
> @amye would it be possible to add @JorTurFer to our distribution list please?

Already done.
