### ISSUE TITLE
Send a notifcation to `#keda` channel before the community call

### ISSUE THREAD

**Issue by zroubalik** [kedacore/governance#44]
We should send a message like this, but more polished.
```
Our community call starts in ~20mins, looking forward to see you there :slightly_smiling_face: https://keda.sh/community/ 
```

https://slack.com/resources/using-slack/how-to-use-reminders-in-slack

**Comment by tomkerkhove** [comment]
This should be done and start on Dec 7th:
![image](https://user-images.githubusercontent.com/4345663/143200460-b372ecf4-6e5d-4055-ac80-d247355068c9.png)
