### ISSUE TITLE
Improve FOSSA project

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#61]
Improve FOSSA project setup given it was not running from the correct GitHub repo.

**Comment by tomkerkhove** [comment]
New link: https://app.fossa.com/projects/custom%2B162%2Fgithub.com%2Fkedacore%2Fkeda/refs/branch/main/147dc874fe2ff0e5e4d936bb1888adf5e93ffef7

**Comment by tomkerkhove** [comment]
Only open issues are missing licenses for which @JorTurFer has opened these:
- https://github.com/dysnix/predictkube-proto/issues/1
- https://github.com/dysnix/predictkube-libs/issues/2

**Comment by JorTurFer** [comment]
At this moment, KEDA passes FOSSA checks https://app.fossa.com/projects/custom%2B162%2Fgithub.com%2Fkedacore%2Fkeda/refs/branch/main/70c45a4324fd279baea2584761a6fbdebb06db4a/preview

**Comment by tomkerkhove** [comment]
Thank you!
