### ISSUE TITLE
CNCF Calendar out of date

### ISSUE THREAD

**Issue by fkautz** [kedacore/governance#64]
The global CNCF calendar has out of date information for KEDA's community calls.

https://www.cncf.io/calendar/

It looks like the time on the calendar is an hour late, the meeting location has changed, the url still points to hackmd, and the hackmd link to find the meeting notes (via aka.ms) is broken.

Would be good to reach out and have the calendar event corrected.

Cheers!

**Comment by tomkerkhove** [comment]
@amye it looks like the CNCF calendar is no longer up to date - Would it be possible to check this please?

I see that you are still part of our invite but you can find the latest info on https://keda.sh/community/

Thanks for reporting @fkautz!

**Comment by amye** [comment]
Please drop a ticket into servicedesk for this, GH is not the preferred method of tracking on these!

**Comment by tomkerkhove** [comment]
I will!

**Comment by tomkerkhove** [comment]
Done - https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1368?created=true

**Comment by tomkerkhove** [comment]
This is now up-to-date: https://tockify.com/cncf.public.events/monthly?search=keda
