### ISSUE TITLE
Document eligibility criteria for Maintainers

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#88]
Document eligibility criteria for Maintainers

See:
- https://docs.google.com/document/d/11Qy7uWginP3gFQVpqnNM4CRp4kQKnEM6FTs2M6pm2o8/edit
- https://github.com/cncf/toc/pull/925#issuecomment-1426421090
- [Guidance](https://contribute.cncf.io/maintainers/github/templates/required/governance-maintainer/)

**Comment by tomkerkhove** [comment]
@kedacore/keda-maintainers I'm going to take a stab at this but currently the only critera I can think of is:
- Be active in our community and contribute
  - We need to explain what that means in terms of types of contributions, "how many", and for how long
- Be kind to people and follow our CoC
- While it should not be a blocker, we should mention something about the company they represent to avoid having too many people from the same company

Anything else you can think of?

**Comment by JorTurFer** [comment]
> Anything else you can think of?

I think that those are more or less the criteria but I'd explain that contributions aren't just code. Code reviews, help with issue triaging/resolving, join to standups (at least from time to time), docs, project management, etc.. are required things. 
IMO being a maintainer involves a lot of different aspects of the project, you don't need to do all of them but just one neither. Of course, it's not only the quantity of the contributions, it's also the quality of them
