### ISSUE TITLE
Launch survey for KEDA end-users

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/governance#99]
Launch survey for KEDA end-users to learn how they are using KEDA and what we can improve.

**Comment by tomkerkhove** [comment]
Survey was created by @zroubalik and is available on https://forms.gle/nC393JzCqK1evjcH9.

Blog post is being published and request with CNCF to share (if possible) has [been opened](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1745?created=true).

**Comment by JorTurFer** [comment]
I'd say that we can close this issue as the survey was done, right?
